/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agungsetiawan.smsbroadcaster.ui;

import IconMakeOver.IconLabel;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author blinkawan
 */
public class DialogTentang extends javax.swing.JDialog {

    /**
     * Creates new form DialogTentang
     */
    public DialogTentang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
//        JLabel jLabel=new JLabel();
//        jLabel.setIcon(new ImageIcon(FormUtama.class.getResource("wood-round-about.png")));
//        jLabel.setBounds(15, 15, 440, 175);
//        this.add(jLabel);
        
        IconLabel ilVLC = new IconLabel();
        ilVLC.setForeground(new Color(255, 255, 255));
        ilVLC.setIconReflect(new ImageIcon(FormUtama.class.getResource("wood-round-about.png")));
        ilVLC.setBounds(15, 15, 440, 300);
        this.add(ilVLC); 
        
        JLabel jLabelBg=new JLabel();
        jLabelBg.setIcon(new ImageIcon(FormUtama.class.getResource("wood1.jpg")));
        jLabelBg.setBounds(0, 0, 588, 420);
        this.add(jLabelBg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInformasi = new javax.swing.JLabel();
        jLabelInformasi2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tentang");

        jLabelInformasi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelInformasi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformasi.setText("Software ini dan source code-nya dapat di download di agung-setiawan.com");

        jLabelInformasi2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelInformasi2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformasi2.setText("secara gratis tanpa biaya. Silahkan digunakan untuk kepentingan belajar saja");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tidak untuk dikomersilkan :p. Silahkan kunjungi http://agung-setiawan.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelInformasi2)
                    .addComponent(jLabelInformasi))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jLabelInformasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInformasi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTentang dialog = new DialogTentang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInformasi;
    private javax.swing.JLabel jLabelInformasi2;
    // End of variables declaration//GEN-END:variables
}
