
package com.agungsetiawan.smsbroadcaster.ui;

import IconMakeOver.IconLabel;
import com.agungsetiawan.smsbroadcaster.backgroundservice.BackgroundService;
import com.agungsetiawan.smsbroadcaster.custom.JButtonTransparant;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author blinkawan
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        IconLabel ilVLC = new IconLabel();
        ilVLC.setForeground(new Color(255, 255, 255));
        ilVLC.setIconReflect(new ImageIcon(FormUtama.class.getResource("undip_150x175.png")));
        ilVLC.setBounds(490, 100, 180, 413);
        jPanel1.add(ilVLC); 
                        
        JLabel jLabel=new JLabel();
        jLabel.setIcon(new ImageIcon(FormUtama.class.getResource("wood1.jpg")));
        jLabel.setBounds(0, 0, 723, 477);
        jPanel1.add(jLabel);
        
        getRootPane().setGlassPane(new JComponent()
		{
            @Override
            public void paintComponent(Graphics g) 
            {
                g.setColor(new Color(0, 0, 0, 100));
                g.fillRect(0, 0, getWidth(), getHeight());
                super.paintComponent(g);
            }
        });
        
       
        
        SwingWorker<Void,Void> swingWorker=new SwingWorker<Void, Void>() {
             BackgroundService backgroundService=new BackgroundService();
             
            @Override
            protected Void doInBackground() throws Exception {
                while(true){
                    try {
                        
                        if(backgroundService.checkStatus()==1){
                           jLabelDate.setText("Servis Berhenti");
                           jButtonServis.setText("Jalankan servis");
                        }else if(backgroundService.checkStatus()==4){
                           jLabelDate.setText("Servis Berjalan");
                           jButtonServis.setText("Hentikan servis");
                        }
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        };
        
        swingWorker.execute();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMenuKirimPesan = new JButtonTransparant();
        jButtonMenuKotakKeluar = new JButtonTransparant();
        jButtonMenuKontak = new JButtonTransparant();
        jButtonMenuGrup = new JButtonTransparant();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonTentang = new JButtonTransparant();
        jLabelDate = new javax.swing.JLabel();
        jButtonServis = new JButtonTransparant();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS Broadcast");
        setPreferredSize(new java.awt.Dimension(732, 470));

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        jButtonMenuKirimPesan.setText("Kirim Pesan");
        jButtonMenuKirimPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuKirimPesanActionPerformed(evt);
            }
        });

        jButtonMenuKotakKeluar.setText("Pesan Terkirim");
        jButtonMenuKotakKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuKotakKeluarActionPerformed(evt);
            }
        });

        jButtonMenuKontak.setText("Kontak");
        jButtonMenuKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuKontakActionPerformed(evt);
            }
        });

        jButtonMenuGrup.setText("Grup");
        jButtonMenuGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuGrupActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(125, 125, 61));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KKN TIM I UNDIP 2014");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SMS Broadcast Desa Kemloko Kecamatan Kranggan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kabupaten Temanggung");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonTentang.setText("Tentang");
        jButtonTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTentangActionPerformed(evt);
            }
        });

        jLabelDate.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDate.setText("jLabel4");

        jButtonServis.setText("jButton1");
        jButtonServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonTentang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMenuKontak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMenuKirimPesan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDate)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonMenuKotakKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jButtonMenuGrup, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jButtonServis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenuKirimPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenuKotakKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenuGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenuKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTentang)
                    .addComponent(jButtonServis))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuKirimPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuKirimPesanActionPerformed
        
        getRootPane().getGlassPane().setVisible(true);
        DialogKirimPesan dialogKirimPesan=new DialogKirimPesan(this, true);
        dialogKirimPesan.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
        
    }//GEN-LAST:event_jButtonMenuKirimPesanActionPerformed

    private void jButtonMenuKotakKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuKotakKeluarActionPerformed
        // TODO add your handling code here:
        getRootPane().getGlassPane().setVisible(true);
        DialogPesanTerkirim dialogPesanTerkirim=new DialogPesanTerkirim(this, true);
        dialogPesanTerkirim.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_jButtonMenuKotakKeluarActionPerformed

    private void jButtonMenuKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuKontakActionPerformed
        getRootPane().getGlassPane().setVisible(true);
        DialogKontak dialogKontak=new DialogKontak(this, true);
        dialogKontak.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_jButtonMenuKontakActionPerformed

    private void jButtonMenuGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuGrupActionPerformed
        getRootPane().getGlassPane().setVisible(true);
        DialogGrup dialogGrup=new DialogGrup(this, true);
        dialogGrup.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_jButtonMenuGrupActionPerformed

    private void jButtonTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTentangActionPerformed
        getRootPane().getGlassPane().setVisible(true);
        DialogTentang dialogTentang=new DialogTentang(this, true);
        dialogTentang.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_jButtonTentangActionPerformed

    private void jButtonServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServisActionPerformed
        // TODO add your handling code here:
        if(jButtonServis.getText().equals("Jalankan servis")){
            try {
                Process process=Runtime.getRuntime().exec("sc start GammuSMSD");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }else if(jButtonServis.getText().equals("Hentikan servis")){
            try {
                Process process=Runtime.getRuntime().exec("sc stop GammuSMSD");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonServisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuGrup;
    private javax.swing.JButton jButtonMenuKirimPesan;
    private javax.swing.JButton jButtonMenuKontak;
    private javax.swing.JButton jButtonMenuKotakKeluar;
    private javax.swing.JButton jButtonServis;
    private javax.swing.JButton jButtonTentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
